name: Code quality
description: A GitHub Action for checking Java code quality

inputs:
  pom_path:
    description: where the pom.xml is located
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "Hello ${{ inputs.who-to-greet }}"
    - uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"
    - name: execute checkstyle
      shell: bash
      run: mvn -f ${{ inputs.pom_path }} checkstyle:checkstyle
    - name: run unit tests
      shell: bash
      run: mvn -f ${{ inputs.pom_path }} test
