name: Build Java App
run-name: Build Java App run name
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults: 
        run:
            working-directory: java-app
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn verify
    - run: ls -l target
    - run: mkdir deploy && cp target/*.jar deploy
    - run: ls -l deploy
    - uses: actions/upload-artifact@v4
      with:
        name: my-java-app
        path: java-app/deploy
