name: test my action
on: workflow_dispatch

jobs:
  the-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/code-quality-java
        with:
          pom_path: "java-app/pom.xml"